### ISSUE TITLE
Error while importing steem into my React.js app

### ISSUE THREAD

**Issue by AusPrinzip** [steemit/steem-js#190]
Cant seem to import steem into my React app index.js.

I correctly installed steem module under node_modules  via

>  npm install steem

, and dependencies installed too via 

> npm install steem --save

Get the following problem:

```
ERROR in ./~/steem/config.json
Module parse failed: /home/james/Desktop/React-MessageBoard-master/node_modules/steem/config.json Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:13)
    at Parser.pp$4.raise (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/james/Desktop/React-MessageBoard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/james/Desktop/React-MessageBoard-master/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/steem/lib/config.js 3:20-45

ERROR in ./~/steem/~/bigi/package.json
Module parse failed: /home/james/Desktop/React-MessageBoard-master/node_modules/steem/node_modules/bigi/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/home/james/Desktop/React-MessageBoard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/home/james/Desktop/React-MessageBoard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at NormalModule.onLoadPitchDone (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at NormalModule.loadPitch (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at NormalModule.doBuild (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/Compilation.js:126:9)
    at /home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/Compilation.js:309:10
    at /home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.<anonymous> (/home/james/Desktop/React-MessageBoard-master/node_modules/tapable/lib/Tapable.js:82:11)
    at NormalModuleFactory.<anonymous> (/home/james/Desktop/React-MessageBoard-master/node_modules/bower-webpack-plugin/lib/bower-plugin.js:108:16)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/james/Desktop/React-MessageBoard-master/node_modules/tapable/lib/Tapable.js:86:13)
    at onDoneResolving (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModuleFactory.js:116:7
 @ ./~/steem/~/bigi/lib/bigi.js 16:15-41

ERROR in ./~/steem/~/ecurve/lib/curves.json
Module parse failed: /home/james/Desktop/React-MessageBoard-master/node_modules/steem/node_modules/ecurve/lib/curves.json Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:13)
    at Parser.pp$4.raise (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/james/Desktop/React-MessageBoard-master/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/james/Desktop/React-MessageBoard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/james/Desktop/React-MessageBoard-master/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/steem/~/ecurve/lib/names.js 3:13-37

```

Here my index.js:

```
import 'core-js/fn/object/assign';
import React from 'react';
import ReactDOM from 'react-dom';
import App from './components/Main';
import steem from 'steem'
// Render the main component into the dom
ReactDOM.render(<App />, document.getElementById('app'));
```

Thanks in advance!

**Comment by bonustrack** [comment]
Can you confirm if this issue has been solved? Thank you.

**Comment by yamadapc** [comment]
You'll need to include `json-loader` in your configuration, please see #196 and the Webpack example added by PR #201
