### ISSUE TITLE
npm postinstall Error: ENOENT

### ISSUE THREAD

**Issue by shroomist** [steemit/steem-js#191]
installing latest releases, after `0.5.18` are giving me the following error:
`Running post install.js Error running postinstall script { Error: ENOENT: no such file or directory, unlink '/Users/mystic/work/react/mysteem/node_modules/steem/index.js' at Object.fs.unlinkSync (fs.js:1053:18) at Object.<anonymous> (/Users/mystic/work/react/mysteem/node_modules/steem/scripts/post-install.js:14:16)
npm -v 5.0.4
node -v v8.0.0`

**Comment by nil1511** [comment]
can you try with `npm install steem@0.5.20-beta.1 --save`?

**Comment by shroomist** [comment]
tried, it throws this 
`mysteem_tmp cnpm install steem@0.5.20-beta.1 --save


> steem@0.5.20-beta.1 postinstall /Users/mystic/work/react/mysteem_tmp/node_modules/steem
> cross-env scripts/post-install.js

module.js:487
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mystic/work/react/mysteem_tmp/node_modules/.bin/cross-env:4:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

**Comment by nil1511** [comment]
What machine are you using? And it is a react-native project?

**Comment by shroomist** [comment]
ok, it worked fine in an empty folder, I have a react-native with expo.io
osx 10.11.6

**Comment by nil1511** [comment]
I am not able to reproduce. 
I have tried
```
npm install exp --global
exp init test
cd test
npm install steem@0.5.20-beta.1 --save
```

**Comment by shroomist** [comment]
you're right it works. closing issue, thanks for help.
