### ISSUE TITLE
latest version of steem npm is brocken

### ISSUE THREAD

**Issue by gropox** [steemit/steem-js#195]
Hi,

last version of NPM module is broken. 

steem@0.5.20-beta.1

```
lotowod@v22017064506850479:~$ npm list steem
/home/lotowod
└── steem@0.5.20-beta.1 

lotowod@v22017064506850479:~$ node --version
v8.1.2
lotowod@v22017064506850479:~$ node
> require("steem")
ReferenceError: __DEV__ is not defined
    at Object.<anonymous> (/home/lotowod/node_modules/steem/lib/index.js:5:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
> 
```

Seems to be related to this commit bcc9c41947886cd6ecb804a32cd43a5c0c4586c7

0.5.19 is working one

**Comment by bonustrack** [comment]
Newest one or < 0.5.19 should work fine. v.@0.5.20-beta.1 should have not been published as default version on NPM we unpublished it.

**Comment by nil1511** [comment]
I have publish `0.5.20` It should work fine
