### ISSUE TITLE
for some tag, getDiscussions retrieve failure

### ISSUE THREAD

**Issue by doojinkang** [steemit/steem-js#198]
I want to make a story list for some "tag", so I used nodejs writing code.
The code is as following.
Retrieve discussion list with query, query has start_author, start_permlink.
~~~~
var steem = require('steem');
var query = {
    tag: 'kr-dev',
    limit: 11,
    start_author: 'kdj',
    start_permlink: 'python-java-1'
};
steem.api.getDiscussionsByCreated(query, function(err, result) {
    if (err) {
        console.log(err);
    }
    for (var i = 0; i < 10; i++) {
        var e = result[i];
        console.log(e.created, e.permlink);
    }
});
~~~~

#### Expected behavior
Retrive the discussions without error.

#### Actual behavior

2017-06-25T16:16:42 python-java-1
/home/doojin/dev/steem/node/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'created' of undefined
    at /home/doojin/dev/steem/node/issue.js:14:22
    at tryCatcher (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/doojin/dev/steem/node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

#### How to reproduce

Run the js code I wrote with node.
Actually I found same issue when accessing https://steemit.com/created/kr-dev
Retrieving stops exact at that points.

**Comment by yamadapc** [comment]
Hard to say what causes you error, it can't be reproduced now.

Two things though:

1. **You should stop the script if there's an error**
```javascript
steem.api.getDiscussionsByCreated(query, function(err, result) {
    if (err) {
        console.log(err);
        return; // <-- This
    }
```

2. **You should iterate the result, not a fixed number; there's no garante there'll actually be 11 posts in the result, there might be a lower number if you're on the last page**
```javascript
    for (var i = 0, len = result.length; i < len; i++) {
        // ...
    }
```
