### ISSUE TITLE
Error: unexpected server response (504)

### ISSUE THREAD

**Issue by Mikepicker** [steemit/steem-js#251]
#### Expected behavior

Calling steem.api.getAccountHistory retrieve information correctly.

#### Actual behavior

Exception thrown:

`Error: unexpected server response (504)
     at ClientRequest._req.on (/app/node_modules/steem/node_modules/ws/lib/WebSocket.js:656:26)
     at emitOne (events.js:96:13)
     at ClientRequest.emit (events.js:188:7)
     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
     at TLSSocket.socketOnData (_http_client.js:363:20)
     at emitOne (events.js:96:13)
     at TLSSocket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:176:18)
     at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)`

#### How to reproduce

It happens sometimes when calling steem.api.getAccountHistory.

#### Environment information

Ubuntu, Node v6.11.2, npm v3.10.10

**Comment by Siko91** [comment]
I get the same one.
I also get 502 errors sometimes.
I am running with Ubuntu as well.
The problem appears both with Node v4.2.6 and Node v6.11.3

This is how the 502 error looks like:

> events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: unexpected server response (502)
    at ClientRequest._req.on (/home/alex/Desktop/steemitbots/resteem-bot/node_modules/ws/lib/WebSocket.js:656:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)

The 504 error looks pretty much the same as with @Mikepicker

**Comment by bonustrack** [comment]
Are you both using the default websocket? It might fail sometimes to respond. I recommend to use `wss://steemd-int.steemit.com` instead.

**Comment by Siko91** [comment]
Just tried it out.
So far it seems to work fine.

One thing that surprised me, was that the indexes of the history (**steem.api.getAccountHistory**) are completely different when using **wss://steemd-int.steemit.com**, compared to the default websocket.

Why is it like that?
Is some information filtered in the **wss://steemd-int.steemit.com**, or did it just start counting later?

**Comment by Mikepicker** [comment]
It looks way more reliable, thanks @bonustrack. Any chance to write it on the docs?

**Comment by ety001** [comment]
This repository has been superseded by a complete 2025 rewrite. The new trunk (`master`, starting at v1.1.0) is a ground-up rewrite of `@steemit/steem-js` and the legacy 0.7.x / 0.8.x code line is archived.

As part of that transition, this issue is being closed because:
- It was filed against the legacy codebase, and the code it references no longer exists in the rewritten trunk.
- The new codebase reimplements the affected areas (RPC routing, transaction serialization, auth/signing, crypto, browser builds) from scratch, so this issue cannot be carried over as-is.

If the problem or request still applies to the rewritten codebase (v1.1.0+ on `master`), please open a new issue against the current trunk with details that reproduce on the new version. Thank you for taking the time to report this originally.
