### ISSUE TITLE
Tests fail with http transport

### ISSUE THREAD

**Issue by jnordberg** [steemit/steem-js#309]
Package tests fail when running against `https://api.steemit.com`

```

  56 passing (2m)
  3 failing

  1) steem.api: streamBlockNumber streams steem transactions:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) steem.api: streamBlock streams steem blocks:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  3) steem.broadcast: comment with options works:
     RPCError: 10 assert_exception: Assert Exception
(now - auth.last_post) > STEEMIT_MIN_REPLY_INTERVAL: You may only comment once every 20 seconds.
    {"now":"2018-01-05T13:21:15","auth.last_post":"2018-01-05T13:21:00"}
    th_a  steem_evaluator.cpp:511 do_apply

    {"o":{"parent_author":"siol","parent_permlink":"test","author":"guest123","permlink":"re-siol-test-20180105t132113189z","title":"Test","body":"This is a test using Steem.js v0.7.0.","json_metadata":"{\"tags\":[\"test\"],\"app\":\"steemjs/0.7.0\"}"}}
    th_a  steem_evaluator.cpp:682 do_apply

    {"op":["comment",{"parent_author":"siol","parent_permlink":"test","author":"guest123","permlink":"re-siol-test-20180105t132113189z","title":"Test","body":"This is a test using Steem.js v0.7.0.","json_metadata":"{\"tags\":[\"test\"],\"app\":\"steemjs/0.7.0\"}"}]}
    th_a  database.cpp:2892 _apply_transaction

    {"trx":{"ref_block_num":34763,"ref_block_prefix":3879642558,"expiration":"2018-01-05T13:31:12","operations":[["comment",{"parent_author":"siol","parent_permlink":"test","author":"guest123","permlink":"re-siol-test-20180105t132113189z","title":"Test","body":"This is a test using Steem.js v0.7.0.","json_metadata":"{\"tags\":[\"test\"],\"app\":\"steemjs/0.7.0\"}"}],["comment_options",{"author":"guest123","permlink":"re-siol-test-20180105t132113189z","max_accepted_payout":"1000000.000 SBD","percent_steem_dollars":10000,"allow_votes":true,"allow_curation_rewards":true,"extensions":[[0,{"beneficiaries":[{"account":"good-karma","weight":2000},{"account":"null","weight":5000}]}]]}]],"extensions":[],"signatures":["207349ffede47806ba166fec404f4e41151e57ae5d4ed6cefad847c981cf9f89677daa239b42503c164593343dad0c870258c5b193c52272fb864ffcc97e807c04"]}}
    th_a  database.cpp:2896 _apply_transaction

    {"trx":{"ref_block_num":34763,"ref_block_prefix":3879642558,"expiration":"2018-01-05T13:31:12","operations":[["comment",{"parent_author":"siol","parent_permlink":"test","author":"guest123","permlink":"re-siol-test-20180105t132113189z","title":"Test","body":"This is a test using Steem.js v0.7.0.","json_metadata":"{\"tags\":[\"test\"],\"app\":\"steemjs/0.7.0\"}"}],["comment_options",{"author":"guest123","permlink":"re-siol-test-20180105t132113189z","max_accepted_payout":"1000000.000 SBD","percent_steem_dollars":10000,"allow_votes":true,"allow_curation_rewards":true,"extensions":[[0,{"beneficiaries":[{"account":"good-karma","weight":2000},{"account":"null","weight":5000}]}]]}]],"extensions":[],"signatures":["207349ffede47806ba166fec404f4e41151e57ae5d4ed6cefad847c981cf9f89677daa239b42503c164593343dad0c870258c5b193c52272fb864ffcc97e807c04"]}}
    th_a  database.cpp:660 push_transaction

    {"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction_synchronous",[{"ref_block_num":34763,"ref_block_prefix":3879642558,"expiration":"2018-01-05T13:31:12","operations":[["comment",{"parent_author":"siol","parent_permlink":"test","author":"guest123","permlink":"re-siol-test-20180105t132113189z","title":"Test","body":"This is a test using Steem.js v0.7.0.","json_metadata":"{\"tags\":[\"test\"],\"app\":\"steemjs/0.7.0\"}"}],["comment_options",{"author":"guest123","permlink":"re-siol-test-20180105t132113189z","max_accepted_payout":"1000000.000 SBD","percent_steem_dollars":10000,"allow_votes":true,"allow_curation_rewards":true,"extensions":[[0,{"beneficiaries":[{"account":"good-karma","weight":2000},{"account":"null","weight":5000}]}]]}]],"extensions":[],"signatures":["207349ffede47806ba166fec404f4e41151e57ae5d4ed6cefad847c981cf9f89677daa239b42503c164593343dad0c870258c5b193c52272fb864ffcc97e807c04"]}]]}
    th_a  websocket_api.cpp:124 on_message
      at new RPCError (src/api/transports/http.js:8:25)
      at src/api/transports/http.js:36:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



error Command failed with exit code 3.
```

(not sure what's up with 3. I only ran the suite once)

**Comment by jnordberg** [comment]
cc @bonustrack @goldibex

**Comment by bonustrack** [comment]
I see there was a comment from @guest123 at `2018-01-05T13:21:03` while your test is failing at `2018-01-05T13:21:15`. You may want to setup another account for it to be sure it's not running by a CI or an user @jnordberg .
