### ISSUE TITLE
RPCError: 3030000 tx_missing_posting_auth: missing required posting authority

### ISSUE THREAD

**Issue by Exanrus** [steemit/steem-js#335]
Getting this error, when  try to post comment

```
steem.broadcast.comment(
                        '5KY...LpS',
                        '',
                        'test',
                        'exan',
                        'posting-test',
                        'test',
                        'test',
                        {},
                        function (err, res) {
                            console.dir(err)
                        });

```
I can create post from steemit.com, but with sttem-js it failed. This code works before changing ws and http addresses. 

```
{ RPCError: 3030000 tx_missing_posting_auth: missing required posting authority
Missing Posting Authority exan
    {"id":"exan","posting":{"weight_threshold":1,"account_auths":[["minnowbooster",1]],"key_auths":[["STM7W9GE84tcxiJoceY1vUPXNepAu6fQ7t7RAr7aFsxTENLmjzzdT",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8PXBzhwUPHcVXWAbyh3dsHqPNsvTpWPa9nyHXLXPbEyjdbB3Yo",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8CRCUwZk1HsFssYubGJTGbX7uJwkcZnRGNkk5rfUrneUsSMjC3",1]]}}
    th_a  transaction.cpp:129 verify_authority

    {"ops":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"sigs":["STM8g1xpfVsZWDgqWUFns8MGZfyBQb59z4vRbySaZTuULd3sgQ3Bi"]}
    th_a  transaction.cpp:172 verify_authority

    {"*this":{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}}
    th_a  transaction.cpp:285 verify_authority

    {"trx":{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}}
    th_a  database.cpp:2897 _apply_transaction

    {"trx":{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}}
    th_a  database.cpp:660 push_transaction

    {"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction_synchronous",[{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}]]}
    th_a  websocket_api.cpp:124 on_message
    at new RPCError (/home/steem-stats/dobryj.kit/node_modules/steem/lib/api/transports/http.js:39:106)
    at /home/steem-stats/dobryj.kit/node_modules/steem/lib/api/transports/http.js:74:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
  cause: 
   { RPCError: 3030000 tx_missing_posting_auth: missing required posting authority
   Missing Posting Authority exan
       {"id":"exan","posting":{"weight_threshold":1,"account_auths":[["minnowbooster",1]],"key_auths":[["STM7W9GE84tcxiJoceY1vUPXNepAu6fQ7t7RAr7aFsxTENLmjzzdT",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8PXBzhwUPHcVXWAbyh3dsHqPNsvTpWPa9nyHXLXPbEyjdbB3Yo",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8CRCUwZk1HsFssYubGJTGbX7uJwkcZnRGNkk5rfUrneUsSMjC3",1]]}}
       th_a  transaction.cpp:129 verify_authority
   
       {"ops":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"sigs":["STM8g1xpfVsZWDgqWUFns8MGZfyBQb59z4vRbySaZTuULd3sgQ3Bi"]}
       th_a  transaction.cpp:172 verify_authority
   
       {"*this":{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}}
       th_a  transaction.cpp:285 verify_authority
   
       {"trx":{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}}
       th_a  database.cpp:2897 _apply_transaction
   
       {"trx":{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}}
       th_a  database.cpp:660 push_transaction
   
       {"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction_synchronous",[{"ref_block_num":22913,"ref_block_prefix":602179865,"expiration":"2018-02-03T18:09:24","operations":[["comment",{"parent_author":"","parent_permlink":"test","author":"exan","permlink":"posting-test","title":"test","body":"test","json_metadata":"{}"}]],"extensions":[],"signatures":["20094aaafa3268190e8ae6b72e0c8019a59e5a58081ac4b6d44e22f4b44ec018b40d455a5c8081a773853d3594812b8c811c955e1d2f6929c3f8815e030825e309"]}]]}
       th_a  websocket_api.cpp:124 on_message
       at new RPCError (/home/steem-stats/dobryj.kit/node_modules/steem/lib/api/transports/http.js:39:106)
       at /home/steem-stats/dobryj.kit/node_modules/steem/lib/api/transports/http.js:74:13
       at process._tickCallback (internal/process/next_tick.js:109:7)
     name: 'RPCError',
     code: 1,
     data: 
      { code: 3030000,
        name: 'tx_missing_posting_auth',
        message: 'missing required posting authority',
        stack: [Object] } },
  isOperational: true,
  code: 1,
  data: 
   { code: 3030000,
     name: 'tx_missing_posting_auth',
     message: 'missing required posting authority',
     stack: [ [Object], [Object], [Object], [Object], [Object], [Object] ] } }
```

**Comment by nextt100** [comment]
same with you. some account error but some ok. why?

**Comment by vlad-saling** [comment]
Seeing same issue when trying to cast a vote.

**Comment by vlad-saling** [comment]
I resolved my by using posting key directly instead of wif:

```
STEEM.broadcast.vote('keyKeyKeyKye', 'myAccount', 'anotherAccount', 'perma-link', 10000, function(err, result) {
	console.log(err, result);
});```

**Comment by BartolomeoItaliano** [comment]
Check this method to get private keys:

var privateKeys = steem.auth.getPrivateKeys(login, passwordOrWIF);`

It works for me, tell me the result.

**Comment by Furiacs** [comment]
@BartolomeoItaliano I tried with posting private key also, same result...

I'm suspecting of my master password's creation. Two reasons:

1 - When I generated the keys using steem.auth.getPrivateKeys (using my master password), I noted my generated public key does't match with public key registered on blockchain (https://steemblockexplorer.com/@"my-username")

2 - My master password doesn't works on steemit.

Does anyone know how to recreate my master password? Is it possible with my username and password?

**Comment by ledux6** [comment]
Same issue I'm using SteemConnect V2 to generate, the code and I tried doing the api call with all the possible keys. Also, on SteemConnect I have every single flag on.

**Comment by Martibis** [comment]
Anyone solve this w/o using posting key directly?

**Comment by ety001** [comment]
This repository has been superseded by a complete 2025 rewrite. The new trunk (`master`, starting at v1.1.0) is a ground-up rewrite of `@steemit/steem-js` and the legacy 0.7.x / 0.8.x code line is archived.

As part of that transition, this issue is being closed because:
- It was filed against the legacy codebase, and the code it references no longer exists in the rewritten trunk.
- The new codebase reimplements the affected areas (RPC routing, transaction serialization, auth/signing, crypto, browser builds) from scratch, so this issue cannot be carried over as-is.

If the problem or request still applies to the rewritten codebase (v1.1.0+ on `master`), please open a new issue against the current trunk with details that reproduce on the new version. Thank you for taking the time to report this originally.
