### ISSUE TITLE
Comment Permlink Bug

### ISSUE THREAD

**Issue by sssunho** [steemit/steem-js#364]
#### Expected behavior

I want to make a comment with `steem.formatter.commentPermlink` and `steem.broadcast.comment`.

#### Actual behavior

My steemit name have '.' like 'abc.de'.
And `commentPermlink` function cannot erase '.' and `steem.broadcast.comment` function make a following error.

```shell
{ RPCError: Assert Exception:false: Invalid permlink character: .
    at new RPCError (/Users/sunny/steemit-translation-web/node_modules/steem/lib/api/transports/http.js:39:106)
    at /Users/sunny/steemit-translation-web/node_modules/steem/lib/api/transports/http.js:74:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  cause: 
   { RPCError: Assert Exception:false: Invalid permlink character: .
    at new RPCError (/Users/sunny/steemit-translation-web/node_modules/steem/lib/api/transports/http.js:39:106)
    at /Users/sunny/steemit-translation-web/node_modules/steem/lib/api/transports/http.js:74:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
     name: 'RPCError',
     code: -32000,
     data: 
      { code: 10,
        name: 'assert_exception',
        message: 'Assert Exception',
        stack: [Array] } },
  isOperational: true,
  code: -32000,
  data: 
   { code: 10,
     name: 'assert_exception',
     message: 'Assert Exception',
     stack: [ [Object], [Object], [Object], [Object], [Object] ] } }
POST /api/v1/trans/request 461 13259.178 ms - 57
/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/Users/sunny/steemit-translation-web/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/Users/sunny/steemit-translation-web/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/sunny/steemit-translation-web/node_modules/express/lib/response.js:256:15)
    at /Users/sunny/steemit-translation-web/routes/api.js:48:9
    at /Users/sunny/steemit-translation-web/models/api.js:162:33
    at tryCatcher (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/sunny/steemit-translation-web/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by BartolomeoItaliano** [comment]
Could you provide example of the code you are trying to execute? Just remember to cover your WIF.

**Comment by BartolomeoItaliano** [comment]
I've checked on steemit.com, what they does this '.' problem and they just remove it from the username, example:
1. User:

> smooth.witness.

2. Link, permlink
https://steemit.com/witness-category/@the-future/re-smoothwitness-32adbe-witness-update-20170131t203228242z#@smooth.witness/re-the-future-re-smoothwitness-32adbe-witness-update-20170131t205743100z.

re-the-future-re-smoothwitness-32adbe-witness-update-20170131t205743100z

I will add such implementation to library then, however I am releasing it under name "steem-js-refactored" cause main fork is abandon.

**Comment by BartolomeoItaliano** [comment]
I've solve this bug on version of steemJs I am releasing. I am making it, because there where more things I need to repair in past. If you want you can find your bug solved in library "steem-js-refactored" version 0.7.8.

Changes are on branch:
https://github.com/steemit/steem-js/issues/364

**Comment by BartolomeoItaliano** [comment]
#366
