### ISSUE TITLE
RPCError on `update_witness` with steem-js

### ISSUE THREAD

**Issue by r351574nc3** [steemit/steem-js#384]
#### Expected behavior

Get some JSON result after a successful witness update.

#### Actual behavior

I am getting this error:
```
Error  { RPCError: Assert Exception:maximum_block_size >= STEEM_MIN_BLOCK_SIZE_LIMIT: 
    at new RPCError (/Users/leoprzybylski/src/github.com/r351574nc3/steem-bot-examples/steem-witness-update/node_modules/steem/lib/api/transports/http.js:39:106)
    at /Users/leoprzybylski/src/github.com/r351574nc3/steem-bot-examples/steem-witness-update/node_modules/steem/lib/api/transports/http.js:74:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  cause: 
   { RPCError: Assert Exception:maximum_block_size >= STEEM_MIN_BLOCK_SIZE_LIMIT: 
    at new RPCError (/Users/leoprzybylski/src/github.com/r351574nc3/steem-bot-examples/steem-witness-update/node_modules/steem/lib/api/transports/http.js:39:106)
    at /Users/leoprzybylski/src/github.com/r351574nc3/steem-bot-examples/steem-witness-update/node_modules/steem/lib/api/transports/http.js:74:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
     name: 'RPCError',
     code: -32000,
     data: 
      { code: 10,
        name: 'assert_exception',
        message: 'Assert Exception',
        stack: [Array] } },
  code: -32000,
  data: 
   { code: 10,
     name: 'assert_exception',
     message: 'Assert Exception',
     stack: [ [Object], [Object], [Object] ] } }
```

Sounds like it's complaining that my `maximum_block_size` isn't set high enough, but I checked with `STEEM_MIN_BLOCK_SIZE_LIMIT` and it definitely is. Even if this value is unset, I think there is a default that should prevent this from happening. Basically, this should never happen and it is.

#### How to reproduce

I tried this two different ways. I tried using `steem.broadcast.updateWitnessAsync`:
```
   steem.broadcast.witnessUpdateAsync(wif, user, 
                "https://steemit.com/witness-category/@r351574nc3/05-27-2018-witness-update", 
                "STMMYPUBLICKEY",
                JSON.stringify({account_creation_fee:"0.100 STEEM",maximum_block_size:131072,sbd_interest_rate:0}),
                "0.000 STEEM"
    )
    .then((results) => {
        console.log("Results ", results)
    })
    .catch((error) => {
        console.log("Error ", error)
    })
```

Then, I also tried using `steem.broadcast.sendAsync`

```
steem.broadcast.sendAsync({
    extensions: [],
    operations: [
        [
            'witness_update',
            {
                owner: user, 
                url: "https://steemit.com/witness-category/@r351574nc3/05-27-2018-witness-update", 
                block_signing_key: "STMMYPUBLICKEY",
                props: JSON.stringify({account_creation_fee:"0.100 STEEM",maximum_block_size:262144,sbd_interest_rate:0}),
                fee: "0.000 STEEM"
            }        
        ]
    ],
  }, { active: wif })
    .then((results) => {
        console.log("Results ", results)
    })
    .catch((error) => {
        console.log("Error ", error)
    })
```
Both result in the same error

#### Environment information

|Setting|Value|
|-------|------|
|Node version|9.4.0|
|NPM Version|6.0.1|
|Mac OS X Version|10.13.4|

**Comment by ety001** [comment]
This repository has been superseded by a complete 2025 rewrite. The new trunk (`master`, starting at v1.1.0) is a ground-up rewrite of `@steemit/steem-js` and the legacy 0.7.x / 0.8.x code line is archived.

As part of that transition, this issue is being closed because:
- It was filed against the legacy codebase, and the code it references no longer exists in the rewritten trunk.
- The new codebase reimplements the affected areas (RPC routing, transaction serialization, auth/signing, crypto, browser builds) from scratch, so this issue cannot be carried over as-is.

If the problem or request still applies to the rewritten codebase (v1.1.0+ on `master`), please open a new issue against the current trunk with details that reproduce on the new version. Thank you for taking the time to report this originally.
