### ISSUE TITLE
steem.api.getAccounts call failling

### ISSUE THREAD

**Issue by thrize** [steemit/steem-js#85]
As of sometime on 16th Feb, calls to ```steem.api.getAccounts``` have been failing.

#### Expected behavior

```steem.api.getAccounts``` responds with well formatted error if a problem, or usual successful response if everything working

#### Actual behavior

Crash when ```steem.api.getAccounts``` is called

#### Stacktrace

Here's an example log output

```
2017-02-17T13:45:53.260009+00:00 app[web.1]: events.js:160
2017-02-17T13:45:53.260013+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-02-17T13:45:53.260014+00:00 app[web.1]:       ^
2017-02-17T13:45:53.260015+00:00 app[web.1]: 
2017-02-17T13:45:53.260015+00:00 app[web.1]: Error: unexpected server response (301)
2017-02-17T13:45:53.260016+00:00 app[web.1]:     at ClientRequest.response (/app/node_modules/ws/lib/WebSocket.js:719:15)
2017-02-17T13:45:53.260017+00:00 app[web.1]:     at ClientRequest.g (events.js:291:16)
2017-02-17T13:45:53.260018+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-02-17T13:45:53.260018+00:00 app[web.1]:     at ClientRequest.emit (events.js:188:7)
2017-02-17T13:45:53.260019+00:00 app[web.1]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
2017-02-17T13:45:53.260020+00:00 app[web.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
2017-02-17T13:45:53.260021+00:00 app[web.1]:     at TLSSocket.socketOnData (_http_client.js:363:20)
2017-02-17T13:45:53.260022+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-02-17T13:45:53.260023+00:00 app[web.1]:     at TLSSocket.emit (events.js:188:7)
2017-02-17T13:45:53.260024+00:00 app[web.1]:     at TLSSocket.Readable.push (_stream_readable.js:134:10)
2017-02-17T13:45:53.260023+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2017-02-17T13:45:53.260025+00:00 app[web.1]:     at TLSWrap.onread (net.js:548:20)
```

#### How to reproduce

It seems to reproduce no matter what account, I have several people reporting this error to me. I presume there is a fundamental problem, probably not with your library but access to the blockchain? The HTTP code is 301, i.e. Moved Permanently, seems to suggest this.

It might also fail for other calls.

Version of library used was 0.4.2, but the issue remains after upgrade to 0.4.7

Also note that Steemit.com was updated very recently, it's not a dependency but the timing is interesting: https://steemit.com/tag/@ausbitbank/release-notes-for-steemit-version-0-1-170216

**Comment by nil1511** [comment]
@thrize current ws server is down. please set `steem.api.setWebSocket('wss://steemd.steemit.com');`. Default ws server will change to `wss://steemd.steemit.com` from next version.

**Comment by thrize** [comment]
Hi @nil1511 thank you.

Do you mean this server is being retired or is it just temporarily down? Do you have a doc reference or anything like that for the server migration? I didn't hear about it.

**Comment by adcpm** [comment]
This issue happen probably because the official websocket url has changed. Can you try to change the url to `wss://steemd.steemit.com`?

**Comment by thrize** [comment]
Yes that fixes it, brilliant :)

Can you can role this fix out into your library? Otherwise it will be broken for all users of it.

**Comment by adcpm** [comment]
@thrize Yes thx, it will solved directly the next version

**Comment by thrize** [comment]
Thanks! :D
