### ISSUE TITLE
Error: Cannot find module './lib/api'

### ISSUE THREAD

**Issue by Netherdrake** [steemit/steem-js#88]
```
W20170218-16:11:20.321(1)? (STDERR) Error: Cannot find module './lib/api'
W20170218-16:11:20.321(1)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170218-16:11:20.321(1)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170218-16:11:20.321(1)? (STDERR)     at Module.require (module.js:353:17)
W20170218-16:11:20.321(1)? (STDERR)     at require (internal/module.js:12:17)
W20170218-16:11:20.321(1)? (STDERR)     at Object.<anonymous> (/home/user/GitHub/SteemSports/steemsports.com/node_modules/steem/index.js:2:8)
W20170218-16:11:20.322(1)? (STDERR)     at Module._compile (module.js:409:26)
W20170218-16:11:20.323(1)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170218-16:11:20.323(1)? (STDERR)     at Module.load (module.js:343:32)
W20170218-16:11:20.323(1)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170218-16:11:20.324(1)? (STDERR)     at Module.require (module.js:353:17)
```

Version:
```
    "steem": "github:adcpm/steem#dev",
```

I tried nuking node_modules and re-installing, but no help.

**Comment by adcpm** [comment]
We removed builded files on the GitHub repo, It's not possible anymore to load Steem.js from GitHub directly, you will need to use the NPM package instead.
